spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animoly?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Coco123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  config:
    import: secrets.yml

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

decorator:
  datasource:
    # p6spy 설정 적용
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j